### ISSUE TITLE
Trying to create a ingress that is not possible

### ISSUE THREAD

**Issue by hydrogen18** [ovrclk/akash#1097]
I tried deploying this simple looking deployment that is based off some awesome-akash stuff

```
---
version: "2.0"

services:
  mongo:
    image: library/mongo:latest
    expose:
      - port: 27017
        as: 27017
        to:
          - service: mongo
  snake:
    image: harish1551/snake-game:latest
    env:
      - DB_HOST=mongo
    depends_on:
      - mongo
    expose:
      - port: 8000
        as: 80
        to:
          - global: true
        accept:
          - snakegame.smartwave.tk

profiles:
  compute:
    snake:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 1G
    mongo:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 128Mi
  placement:
    westcoast:
      pricing:
        snake: 
          denom: uakt
          amount: 90000
        mongo: 
          denom: uakt
          amount: 90000

deployment:
  snake:
    westcoast:
      profile: snake
      count: 1
  mongo:
    westcoast:
      profile: mongo
      count: 1
```

and the deployment never comes fully online 

```
$ ~/ovrclk/akash/akash --chain-id=local --home=$PWD/home --node=tcp://147.75.105.135:26657 --keyring-backend=test --from=user0 --log_level=trace  deploy create snake.yaml
I[2021-02-16|07:44:45.672] tx sent successfully                         hash=F8B9A580D37C5F7762293E06DE952BFA22B1D08D6AD8F53C1F78EEE0D1F2E32F code=0 codespace= action=create-deployment dseq=14519
I[2021-02-16|07:44:46.673] deployment created                           addr=akash19dnhammcj3vf9dzgmtgg7pc8ujecn5azlzcu09 dseq=14519
I[2021-02-16|07:44:46.673] order for deployment created                 addr=akash19dnhammcj3vf9dzgmtgg7pc8ujecn5azlzcu09 dseq=14519 oseq=1
I[2021-02-16|07:44:51.921] bid for order created                        addr=akash19dnhammcj3vf9dzgmtgg7pc8ujecn5azlzcu09 dseq=14519 oseq=1 price=26322uakt
D[2021-02-16|07:44:51.921] Processing bid                               
D[2021-02-16|07:44:51.921] All groups have at least one bid             
I[2021-02-16|07:45:06.922] Done waiting on bids                         qty=1
I[2021-02-16|07:45:06.922] Winning bid                                  gseq=1 price=26322uakt provider=akash16gfc7yfktrupn58mv8sjp7pvyd09jsh70whnzq
I[2021-02-16|07:45:07.964] All expected leases created                  addr=akash19dnhammcj3vf9dzgmtgg7pc8ujecn5azlzcu09 dseq=14519
I[2021-02-16|07:45:07.964] lease for order created                      addr=akash19dnhammcj3vf9dzgmtgg7pc8ujecn5azlzcu09 dseq=14519 oseq=1 price=26322uakt
I[2021-02-16|07:45:07.964] Waiting on leases to be ready                leaseQuantity=1
D[2021-02-16|07:45:07.965] Checking status of lease                     lease=akash19dnhammcj3vf9dzgmtgg7pc8ujecn5azlzcu09/14519/1/1/akash16gfc7yfktrupn58mv8sjp7pvyd09jsh70whnzq
I[2021-02-16|07:45:08.465] sending manifest to provider                 action=send-manifest provider=akash16gfc7yfktrupn58mv8sjp7pvyd09jsh70whnzq dseq=14519
D[2021-02-16|07:45:08.804] Could not get lease status                   lease=akash19dnhammcj3vf9dzgmtgg7pc8ujecn5azlzcu09/14519/1/1/akash16gfc7yfktrupn58mv8sjp7pvyd09jsh70whnzq err="remote server returned 503"
I[2021-02-16|07:45:24.612] service ready                                lease=akash19dnhammcj3vf9dzgmtgg7pc8ujecn5azlzcu09/14519/1/1/akash16gfc7yfktrupn58mv8sjp7pvyd09jsh70whnzq service=mongo
I[2021-02-16|07:45:39.675] service ready                                lease=akash19dnhammcj3vf9dzgmtgg7pc8ujecn5azlzcu09/14519/1/1/akash16gfc7yfktrupn58mv8sjp7pvyd09jsh70whnzq service=snake
I[2021-02-16|07:45:39.676] lease ready                                  leaseID=akash19dnhammcj3vf9dzgmtgg7pc8ujecn5azlzcu09/14519/1/1/akash16gfc7yfktrupn58mv8sjp7pvyd09jsh70whnzq
Error: All attempts fail:
#1: remote server returned 404
#2: remote server returned 404
#3: remote server returned 404
#4: remote server returned 404
#5: remote server returned 404
#6: remote server returned 404
#7: remote server returned 404
#8: remote server returned 404
#9: remote server returned 404
#10: remote server returned 404

```

The provider logs this, I think we may have a bug when creating ingress objects

```
Feb 16 13:45:39 dfw0 akash[257098]: E[2021-02-16|13:45:39.709] ingresses.networking.k8s.io "mongo" not found module=provider-cluster-kube
Feb 16 13:45:39 dfw0 akash[257098]: E[2021-02-16|13:45:39.949] ingresses.networking.k8s.io "mongo" not found module=provider-cluster-kube
Feb 16 13:45:40 dfw0 akash[257098]: E[2021-02-16|13:45:40.284] ingresses.networking.k8s.io "mongo" not found module=provider-cluster-kube
Feb 16 13:45:40 dfw0 akash[257098]: E[2021-02-16|13:45:40.874] ingresses.networking.k8s.io "mongo" not found module=provider-cluster-kube
Feb 16 13:45:41 dfw0 akash[257098]: E[2021-02-16|13:45:41.793] ingresses.networking.k8s.io "mongo" not found module=provider-cluster-kube
Feb 16 13:45:43 dfw0 akash[257098]: E[2021-02-16|13:45:43.538] ingresses.networking.k8s.io "mongo" not found module=provider-cluster-kube
Feb 16 13:45:46 dfw0 akash[257098]: E[2021-02-16|13:45:46.846] ingresses.networking.k8s.io "mongo" not found module=provider-cluster-kube
Feb 16 13:45:53 dfw0 akash[257098]: E[2021-02-16|13:45:53.325] ingresses.networking.k8s.io "mongo" not found module=provider-cluster-kube
Feb 16 13:46:06 dfw0 akash[257098]: E[2021-02-16|13:46:06.227] ingresses.networking.k8s.io "mongo" not found module=provider-cluster-kube
Feb 16 13:46:31 dfw0 akash[257098]: E[2021-02-16|13:46:31.960] ingresses.networking.k8s.io "mongo" not found module=provider-cluster-kube
```
