### ISSUE TITLE
provider: no bids if service count is not 1

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#1122]
This _may_ be a pricing issue, but I don't think that it is.

```yaml
deployment:
  web:
    primary:
      profile: web
      count: 2
```
