### ISSUE TITLE
provider: hostnames reserved after lease is closed

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#1123]
If a manifest has a `accept:` host, then that host is not able to be used again, even after the deployment is closed.

```yaml
      - port: 3000
        as: 80
        accept:
          - "edgenet.decloud.bigdipper.live"
        to:
          - global: true
```
