### ISSUE TITLE
Remove all references to "deploy via kustomize" instructions

### ISSUE THREAD

**Issue by hydrogen18** [ovrclk/akash#1204]
We no longer support kustomize for running nodes or providers - remove references to it from docs.akash.network

-----

Discord user earlyster reported he had to add this to copy the cert over

```
secretGenerator:
  ##
  # required values:
  ##
  - name: akash-provider-keys
    files:
      - key.txt
      - key-pass.txt
      - provider-cert.pem
```

Remove support entirely as we don't want to support this anymore

- [ ] Remove all references to it everywhere.
