### ISSUE TITLE
sdl: compute profile name assumed to be service name

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#1215]
`GetDeploymentGroups()` [uses the profile name](https://github.com/ovrclk/akash/blob/9b11cf65d6ec58ef31a66b639fc20f9d825b795d/sdl/v2.go#L123) when determining endpoints to include in a group instead of the service name.

This causes sdl files like the one below to not have any endpoints in their groups or orders.  Wen sending the manifest, validation fails because of an endpoint count mismatch ([`Manifest()`](https://github.com/ovrclk/akash/blob/9b11cf65d6ec58ef31a66b639fc20f9d825b795d/sdl/v2.go#L170) apparently does the right thing).

```yaml
---
version: "2.0"
services:
  web:
    image: ourwebapp
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
profiles:
  compute:
    frontend:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          size: 32Gi
  placement:
    westcoast:
      pricing:
        frontend:
          denom: uakt
          amount: 100

deployment:
  web:
    westcoast:
      profile: frontend
      count: 1
```
