### ISSUE TITLE
Connect IBC to Cosmos Hub

### ISSUE THREAD

**Issue by ngehani** [ovrclk/akash#1226]
April 24th when the IBC proposal is scheduled to pass. https://akash.aneka.io/proposals/6

We want to connect to Cosmos Hub and see a ATOM <> AKT swap preferably scheduled to happen on the same day

Solution:
- we have to run a relayer.

**Comment by anilCSE** [comment]
@akhilkumarpilli can start a relayer

**Comment by ngehani** [comment]
> @akhilkumarpilli can start a relayer

Would you please update with a timeline in the Slack channel?

**Comment by boz** [comment]
from @akhilkumarpilli on slack:

> Relayer setup is done. Made a successful transaction between akashnet-2 and cosmoshub-4: https://akash.aneka.io/txs/DCBD6E451A7EF0B20EA26219E9D856F130D05FC38F4DA8AE2320EB59F0FF0FB8
Here is the path config with client,channel and connection identifiers:

```yaml
src:
      chain-id: akashnet-2
      client-id: 07-tendermint-8
      connection-id: connection-2
      channel-id: channel-0
      port-id: transfer
      order: unordered
      version: ics20-1
    dst:
      chain-id: cosmoshub-4
      client-id: 07-tendermint-146
      connection-id: connection-192
      channel-id: channel-95
      port-id: transfer
      order: unordered
      version: ics20-1
    strategy:
      type: naive
```
