### ISSUE TITLE
pagination during cert query does not work

### ISSUE THREAD

**Issue by troian** [ovrclk/akash#1240]
```
ericu@ericu-acer-laptop:~/ovrclk_keybase/providers$ akash query cert --chain-id akashnet-2 list --owner akash1ccktptfkvdc67msasmesuy5m7gpc76z75kukpz --state valid --limit=1
certificates: []
pagination: null
ericu@ericu-acer-laptop:~/ovrclk_keybase/providers$ akash query cert --chain-id akashnet-2 list --owner akash1ccktptfkvdc67msasmesuy5m7gpc76z75kukpz --state valid --limit=2
certificates: []
pagination: null
ericu@ericu-acer-laptop:~/ovrclk_keybase/providers$ akash query cert --chain-id akashnet-2 list --owner akash1ccktptfkvdc67msasmesuy5m7gpc76z75kukpz --state valid 
certificates:
- certificate:
    cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNNakNDQWRpZ0F3SUJBZ0lJRm5vY2VlVS9USzR3Q2dZSUtvWkl6ajBFQXdJd1NqRTFNRE1HQTFVRUF4TXMKWVd0aGMyZ3hZMk5yZEhCMFptdDJaR00yTjIxellYTnRaWE4xZVRWdE4yZHdZemMyZWpjMWEzVnJjSG94RVRBUApCZ1ZuZ1FVQ0JoTUdkakF1TUM0eE1CNFhEVEl4TURReU9ERTVNekl3TlZvWERUSXlNRFF5T0RFNU16SXdOVm93ClNqRTFNRE1HQTFVRUF4TXNZV3RoYzJneFkyTnJkSEIwWm10MlpHTTJOMjF6WVhOdFpYTjFlVFZ0TjJkd1l6YzIKZWpjMWEzVnJjSG94RVRBUEJnVm5nUVVDQmhNR2RqQXVNQzR4TUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRTk0S2h3M09ubVJDa0ViR0plazJJYWJ0TSthN0ZwUTQyZzVBWWJiYkRZQXoxVmp4clk5WXRBT1hZCk4zUUxGOUdQUlJwQnhFUmZJK3A0aEdXTjRpZzFmS09CcHpDQnBEQU9CZ05WSFE4QkFmOEVCQU1DQkRBd0hRWUQKVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0lHQ0NzR0FRVUZCd01CTUF3R0ExVWRFd0VCL3dRQ01BQXdMZ1lEVlIwUgpCQ2N3SllJamNISnZkbWxrWlhJdVlXMXpNWEF3TG0xaGFXNXVaWFF1WVd0aGMyaHBZVzR1YVc4d05RWURWUjBlCkFRSC9CQ3N3S2FBbk1DV0NJM0J5YjNacFpHVnlMbUZ0Y3pGd01DNXRZV2x1Ym1WMExtRnJZWE5vYVdGdUxtbHYKTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUJiUzB0QlUvWHBJcGRHbktJR0pXcVFKdndIT2hLd255cGlkdWJ5egpNNDVPQWlFQXhPNVV3YlB5T0FWc2dTeHBIcGJUbEV3Q2dWRWxTdEc0cXd5NG9pVmwrKzg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    pubkey: LS0tLS1CRUdJTiBFQyBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFOTRLaHczT25tUkNrRWJHSmVrMklhYnRNK2E3RgpwUTQyZzVBWWJiYkRZQXoxVmp4clk5WXRBT1hZTjNRTEY5R1BSUnBCeEVSZkkrcDRoR1dONGlnMWZBPT0KLS0tLS1FTkQgRUMgUFVCTElDIEtFWS0tLS0tCg==
    state: valid
  serial: "1619638325855866030"
pagination: null
```

/cc @hydrogen18
