### ISSUE TITLE
Command deploy instruction has no effect

### ISSUE THREAD

**Issue by tombeynon** [ovrclk/akash#1301]
The `command` instruction in the deploy SDL seems to have no effect. I've tried string and array syntax but the default command always seems to run on Akash.

Example SDL below; this will start nginx by default, but should be overridden to `echo "hello world"`. On Akash this will incorrectly start nginx.

```
---
version: "2.0"

services:
  hello-world:
    image: "tombeynon/akash-hello-world:release-v0.1.1"
    command: ["echo", "\"hello world\""]
    expose:
      - port: 9999 # required global service
        to:
          - global: true

profiles:
  compute:
    hello-world:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 0.1Gi
        storage:
          size: 0.1Gi
  placement:
    dcloud:
      pricing:
        hello-world:
          denom: uakt
          amount: 10

deployment:
  hello-world:
    dcloud:
      profile: hello-world
      count: 1
```
