### ISSUE TITLE
Error connecting two services to a third

### ISSUE THREAD

**Issue by tombeynon** [ovrclk/akash#1303]
Connecting a single service to another with `expose.to` works great. Introducing a second service connected in the same way causes a `provider error messsage: kube: no global services for lease` error message and the two dependent containers don't start. Removing the `expose.to` instructions for one of the containers will then fix the error, and (incorrectly?) both containers do have access to the third. This functions as a workaround.

The below SDL works until you uncomment `- service: test-2`. I tried a few variations of this (duplicating the whole `port` section etc) with no luck.

```
---
version: "2.0"

services:
  test-1:
    image: tombeynon/hello-world-curl-test
    depends_on:
      - service: hello-world
  test-2:
    image: tombeynon/hello-world-curl-test
    depends_on:
      - service: hello-world
  hello-world:
    image: tombeynon/akash-hello-world:release-v0.1.1
    expose:
      - port: 80
        to:
          - service: test-1
          # - service: test-2
      - port: 9999 # required global service
        to:
          - global: true

profiles:
  compute:
    test-1:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 0.1Gi
        storage:
          size: 0.1Gi
    test-2:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 0.1Gi
        storage:
          size: 0.1Gi
    hello-world:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 0.1Gi
        storage:
          size: 0.1Gi
  placement:
    dcloud:
      pricing:
        test-1:
          denom: uakt
          amount: 10
        test-2:
          denom: uakt
          amount: 10
        hello-world:
          denom: uakt
          amount: 10

deployment:
  test-1:
    dcloud:
      profile: test-1
      count: 1
  test-2:
    dcloud:
      profile: test-2
      count: 1
  hello-world:
    dcloud:
      profile: hello-world
      count: 1
```

**Comment by hydrogen18** [comment]
My provider spit this out when I tried your SDL

```
I[2021-07-09|14:03:40.420] manifest received                            module=provider-cluster cmp=service
I[2021-07-09|14:03:40.434] No deployments found for                     module=provider-cluster-kube leasenamespace=4homp4j2rl698e0k9f65boov74ujgsotmr5uks5qp33gs
D[2021-07-09|14:03:40.447] provider/cluster/kube/builder: created service module=kube-builder service="&Service{ObjectMeta:{hello-world      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[akash.network:true akash.network/manifest-service:hello-world akash.network/namespace:4homp4j2rl698e0k9f65boov74ujgsotmr5uks5qp33gs] map[] [] []  []},Spec:ServiceSpec{Ports:[]ServicePort{ServicePort{Name:1-80,Protocol:TCP,Port:80,TargetPort:{0 80 },NodePort:0,AppProtocol:nil,},ServicePort{Name:2-80,Protocol:TCP,Port:80,TargetPort:{0 80 },NodePort:0,AppProtocol:nil,},},Selector:map[string]string{akash.network: true,akash.network/manifest-service: hello-world,akash.network/namespace: 4homp4j2rl698e0k9f65boov74ujgsotmr5uks5qp33gs,},ClusterIP:,Type:ClusterIP,ExternalIPs:[],SessionAffinity:,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,IPFamily:nil,TopologyKeys:[],},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{},},},}"
E[2021-07-09|14:03:40.448] applying local service                       module=provider-cluster-kube err="Service \"hello-world\" is invalid: spec.ports[1]: Duplicate value: core.ServicePort{Name:\"\", Protocol:\"TCP\", AppProtocol:(*string)(nil), Port:80, TargetPort:intstr.IntOrString{Type:0, IntVal:0, StrVal:\"\"}, NodePort:0}" lease=akash1lz5dvghpxy0uv2fvags00d5wr9h8kka8g3hekj/1002/1/1/akash1uvj4vc3m7pgh5n8jezev08y96nhmgap73z7kqv service=hello-world
E[2021-07-09|14:03:40.448] execution error                              module=provider-cluster cmp=service cmp=deployment-manager lease=akash1lz5dvghpxy0uv2fvags00d5wr9h8kka8g3hekj/1002/1/1/akash1uvj4vc3m7pgh5n8jezev08y96nhmgap73z7kqv manifest-group=dcloud state=deploy-active err="Service \"hello-world\" is invalid: spec.ports[1]: Duplicate value: core.ServicePort{Name:\"\", Protocol:\"TCP\", AppProtocol:(*string)(nil), Port:80, TargetPort:intstr.IntOrString{Type:0, IntVal:0, StrVal:\"\"}, NodePort:0}"

```

unsure what the cause is exactly but the issue is legitimate.

**Comment by boz** [comment]
```yaml
    depends_on:
      - service: hello-world
  test-2:
    image: tombeynon/hello-world-curl-test
    depends_on:
      - service: hello-world
```

`depends_on` is a no-op right now.
