### ISSUE TITLE
Valid domain names in manifest are rejected

### ISSUE THREAD

**Issue by tombeynon** [ovrclk/akash#1326]
It seems that domains with a dash in them (including subdomains with a dash) are rejected by Akash when they are a valid domain. 

This was raised by a user of my deploy tool at https://github.com/tombeynon/akash-deploy/issues/6, and I've encountered this before with subdomains.

Example error:

```
Error: invalid manifest: service "web" has invalid hostname "maurits-bos.me"
```

**Comment by anthonyrosa** [comment]
Adding this comment at the request of Mr. Beynon. On July 18, while helping an individual deploy their personal website on Akash, said individual reported he was receiving "Deployment requires 5000000uakt escrow" errors and "if i try again, i get something else." Once that error resolved, he was then receiving "Error: invalid manifest: service 'web' has invalid hostname 'maurits-bos.me'" messages. I took over the deployment to troubleshoot and experienced the same escrow error. I added 5 AKT to settle this problem and then revoked my current certificate and created a new one. This led to a successful manifest update and maurits-bos.me resolves properly on https. However, despite having a CNAME set up for www.maurits-bos.me, 404 errors are sent when attempting to access the page with a www.

**Comment by anthonyrosa** [comment]
Issue was resolved by adding accept: -www.maurits-bos.me in addition to maurits-bos.me

**Comment by tombeynon** [comment]
Yea apologies for the confusion, the linked issue is unrelated. However the domain validation is still an issue, as can be seen with this failing manifest. `valid-domain.tombeynon.co.uk` should work fine, however you cannot create a deployment with a subdomain with a dash like this. The error returned is `Error: invalid manifest: service "web" has invalid hostname "valid-domain.tombeynon.co.uk"`

```
---
version: "2.0"

services:
  web:
    image: tombeynon/akash-hello-world:release-v0.1.1
    expose:
      - port: 80
        as: 80
        accept:
          - valid-domain.tombeynon.co.uk
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    dcloud:
      pricing:
        web:
          denom: uakt
          amount: 1

deployment:
  web:
    dcloud:
      profile: web
      count: 1
```
