### ISSUE TITLE
Deployment Resetting While running 'npm ci && npm run build'

### ISSUE THREAD

**Issue by lightiv** [ovrclk/akash#1377]
While running ```npm ci && npm run build``` to build a git project the deployment disconnects and when I re-connect the installation is reset.  For example, I git clone a project before installing npm.  After reconnect the git project folder is gone.  This has happened twice.

Provider lease events need to have a correct date stamp:
```
{
  "type": "Normal",
  "time": "0001-01-01T00:00:00Z",
  "reason": "ScalingReplicaSet",
  "note": "Scaled up replica set web-8457885f58 to 1",
  "object": {
    "kind": "Deployment",
    "namespace": "lq4hllol0q2elt804lv410e1f43jjrlvicrf7ahb3jhbu",
    "name": "web"
  }
}
```
Lease:

```
leases:
- escrow_payment:
    account_id:
      scope: deployment
      xid: akash14s4tlmlvy0vsps05csf8l80m7nqxmau38tehp9/2695163
    balance:
      amount: "0"
      denom: uakt
    owner: akash14c4ng96vdle6tae8r4hc2w4ujwrsh3x9tuudk0
    payment_id: 1/1/akash14c4ng96vdle6tae8r4hc2w4ujwrsh3x9tuudk0
    rate:
      amount: "2"
      denom: uakt
    state: open
    withdrawn:
      amount: "0"
      denom: uakt
  lease:
    created_at: "2695179"
    lease_id:
      dseq: "2695163"
      gseq: 1
      oseq: 1
      owner: akash14s4tlmlvy0vsps05csf8l80m7nqxmau38tehp9
      provider: akash14c4ng96vdle6tae8r4hc2w4ujwrsh3x9tuudk0
    price:
      amount: "2"
      denom: uakt
    state: active
pagination:
  next_key: null
  total: "0"
``` 
Deploy.yml
```---
version: "2.0"

services:
  web:
    image: .../cosmos-node-ready
    env:
      - sshport=22322
      - pubkey=
    expose:
      - port: 3000
        accept:
          - domain.com
        to:
          - global: true
      - port: 22322
        as: 22322
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 512Mi

  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        web:
          denom: uakt
          amount: 10

deployment:
  web:
    dcloud:
      profile: web
      count: 1
```
