### ISSUE TITLE
BUG: the total of node Ports can't be incremented/decremented

### ISSUE THREAD

**Issue by arno01** [ovrclk/akash#1554]
It looks like that one can't add/remove the node Ports in their deployment (the default range 30000:32767), i.e.

```
  app:
    image: gcr.io/google_containers/echoserver:1.10
    expose:
      - port: 8080  ## this port can be changed w/o issues
        as: 80 ## this can't
        to:
          - global: true
# adding the 8081 port and running `akash tx deployment update` + `akash provider send-manifest` 
      - port: 8081
        to:
          - global: true
```

- changing the container port worked for me;
- adding a new container port (non-80 one) - did not;
- changing the "as" [external] port from 80 to 81 - did not. that's likely because 80/tcp is getting exposed in a different way (i.e. non k8s's-nodePort)

The error:

```
[{"provider":"akash1u5cdg7k3gl43mukca4aeultuz8x2j68mgwn28e","status":"FAIL","error":{"Status":500,"Message":"invalid manifest: mismatch on number of endpoints 1 != 0\n"}}]
```

Ref.
https://discord.com/channels/747885925232672829/771909909335506955/963413362962751528

**Comment by arno01** [comment]
changing the nodePort value is working, i.e.

```
# before
      - port: 8081
        as: 1234  # mapped to 32065
        to:
          - global: true
# after
      - port: 8081
        as: 1235 # got remapped to 32130
        to:
          - global: true
# after
      - port: 8082 # changed w/o issues
        as: 1235 # the mapped port 32130 did not change as expected
        to:
          - global: true
```
