### ISSUE TITLE
Adding a lease fails when the SDL specifies some set of characters

### ISSUE THREAD

**Issue by tidrolpolelsef** [ovrclk/akash#1656]
In some cases, creating the IP with a lease as an object in kubernetes fails

```
 E[2022-07-12|13:21:17.221] failed adding IP declaration                 module=provider-cluster cmp=provider cmp=service cmp=deployment-manager lease=akash140rwd5t4jxfldtj3t9l0c2p0yd228ce9u7e39y/201/1/1/akash193fcgzzv7rjtrmu6pvtnk6ahru3dltdk92fp43 manifest-group=akash service=librespeed port=80 endpoint=static_ip err="ProviderLeasedIP.akash.network \"akash140rwd5t4jxfldtj3t9l0c2p0yd228ce9u7e39y-ip-static_ip-tcp-80\" is invalid: metadata.name: Invalid value: \"akash140rwd5t4jxfldtj3t9l0c2p0yd228ce9u7e39y-ip-static_ip-tcp-80\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric cha ││ E[2022-07-12|13:21:17.221] execution error                              module=provider-cluster cmp=provider cmp=service cmp=deployment-manager lease=akash140rwd5t4jxfldtj3t9l0c2p0yd228ce9u7e39y/201/1/1/akash193fcgzzv7rjtrmu6pvtnk6ahru3dltdk92fp43 manifest-group=akash state=deploy-active err="ProviderLeasedIP.akash.network \"akash140rwd5t4jxfldtj3t9l0c2p0yd228ce9u7e39y-ip-static_ip-tcp-80\" is invalid: metadata.name: Invalid value: \"akash140rwd5t4jxfldtj3t9l0c2p0yd228ce9u7e39y-ip-static_ip-tcp-80\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com' ││ D[2022-07-12|13:21:17.226] purged ips                                   module=provider-cluster cmp=provider cmp=service cmp=deployment-manager lease=akash140rwd5t4jxfldtj3t9l0c2p0yd228ce9u7e39y/201/1/1/akash193fcgzzv7rjtrmu6pvtnk6ahru3dltdk92fp43 manifest
```

I added code to work around this, but it must be missing a case somewhere in there.

SDL used was 

```
---
version: "2.0"

services:
  librespeed:
    image: adolfintel/speedtest
    expose:
      - port: 80
        to:
          - global: true
            ip: "static_ip"
    env:
      - MODE=standalone
      - TITLE=Akash Librespeed Test
      - WEBPORT=80
      #- TELEMETRY=
      #- ENABLE_ID_OBFUSCATION=
      #- REDACT_IP_ADDRESSES=
      #- PASSWORD=
      #- EMAIL=
      #- IPINFO_APIKEY=
      #- DISABLE_IPINFO=
      #- DISTANCE=
      #Check https://github.com/librespeed/speedtest/blob/master/doc_docker.md#standalone-mode for detailed descriptions
profiles:
  compute:
    librespeed:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    akash:
      pricing:
        librespeed:
          denom: uakt
          amount: 10000
deployment:
  librespeed:
    akash:
      profile: librespeed
      count: 1
endpoints:
  static_ip:
    kind: ip
```
