### ISSUE TITLE
cannot query account balances before the mainnet upgrade height 5629650

### ISSUE THREAD

**Issue by andy108369** [ovrclk/akash#1666]
## cannot query account balances before the mainnet upgrade

I am using full (archive) RPC node (tried different ones, ours, forbole, ...) as well as different akash binary, v0.14.x, v0.15.x and v0.16.4.

Cannot query balances before the mainnet upgrade, whilst can query the market module without issues.

[`5629650`](https://www.mintscan.io/akash/blocks/5629650) mainnet upgrade height - 2 months ago (`2022-04-26 19:45:09`) in [prop #12](https://www.mintscan.io/akash/proposals/19). 

```
# akash query bank balances --height 5629700 akash1vky0uh4wayh9npd74uqesglpaxwymynnspf6a4
balances:
- amount: "14619232085"
  denom: uakt
pagination:
  next_key: null
  total: "0"

# akash query bank balances --height 5629600 akash1vky0uh4wayh9npd74uqesglpaxwymynnspf6a4
balances: []
pagination:
  next_key: null
  total: "0"
```

Can query leases without issues though:

```
# akash query market lease list --height 5629000 --provider akash1vky0uh4wayh9npd74uqesglpaxwymynnspf6a4 --gseq 0 --oseq 0 --page 1 --limit 200 --state active -o json | jq -r '.leases | length'
98
```

Could be that there is a similar to https://github.com/ovrclk/akash/pull/1605/files fix is needed?

----

### Precision falls by 100 for older than 25 days blocks

Another interesting thing I've noticed is that the precision falls by 100 for older than 25 days blocks. I.e. when I query the RPC node for `63893XX` height where `XX` is anything but not `00` would return no items, example:

```
# akash query bank balances --height 6389320 akash1vky0uh4wayh9npd74uqesglpaxwymynnspf6a4
balances: []
pagination:
  next_key: null
  total: "0"

# akash query bank balances --height 6389300 akash1vky0uh4wayh9npd74uqesglpaxwymynnspf6a4
balances:
- amount: "14502093352"
  denom: uakt
pagination:
  next_key: null
  total: "0"
```

> I am dropping the precision by 100, i.e. `BLOCK=$(($BLOCK - $(expr $BLOCK % 100)))` to make sure I am always getting the results when querying the blockchain for historical events (i.e. older than 25 days).
