### ISSUE TITLE
unable to set custom hostname

### ISSUE THREAD

**Issue by gosuri** [ovrclk/akash#351]
Deployed a workload with custom hostname with the below config:

```yaml
---
version: "1.0"

services:
  web:
    image: quay.io/ovrclk/demo-app
    accept:
      - example.com
    expose:
      - port: 80
        as: 80
        to:
          - global: true

profiles:
  compute:
    web:
      cpu: "100m"
      memory: "512Mi"
      disk: "512Mi"
  placement:
    san-jose:
      attributes:
        region: sjc
      pricing:
        web: .0012

deployment:
  web:
    san-jose:
      profile: web
      count: 1
```
and got the below output:
```
71de7facbc40fd9e5e3f046007fbbcc7fa556119fe606be2fcdcb3b4e86ee590
Waiting...
Group 1/1 Fulfillment: 71de7facbc40fd9e5e3f046007fbbcc7fa556119fe606be2fcdcb3b4e86ee590/1/2/cf444e07a1fdf130808233b5f90b2d111be6f369a3f48f59993f956efbb9bb43 [price=70]
Group 1/1 Lease: 71de7facbc40fd9e5e3f046007fbbcc7fa556119fe606be2fcdcb3b4e86ee590/1/2/cf444e07a1fdf130808233b5f90b2d111be6f369a3f48f59993f956efbb9bb43 [price=70]
Sending manifest to http://provider.sjc.arrakis.akashtest.net...
Service URIs for provider: cf444e07a1fdf130808233b5f90b2d111be6f369a3f48f59993f956efbb9bb43
	web: web.0cd48889-850d-4ae1-bd1c-0b37a315783d.147-75-89-53.aksh.io
```

The site resolves to the provided hostname but not for `example.com`:

```sh
$ curl web.0cd48889-850d-4ae1-bd1c-0b37a315783d.147-75-89-53.aksh.io # works
$ curl -H 'HOST:example.com' web.0cd48889-850d-4ae1-bd1c-0b37a315783d.147-75-89-53.aksh.io #fails
```

Further investigation on the kube cluster reveals the ingress did not set the hostname:

```sh
$ kubectl get ingress web -o yaml -n 931021b655b6f14ae458b678f7fc891c515cccaf
```
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: 2018-08-14T00:26:20Z
  generation: 1
  labels:
    akash.network: "true"
    akash.network/manifest-service: web
  name: web
  namespace: 931021b655b6f14ae458b678f7fc891c515cccaf
  resourceVersion: "1920"
  selfLink: /apis/extensions/v1beta1/namespaces/931021b655b6f14ae458b678f7fc891c515cccaf/ingresses/web
  uid: aae9be42-9f58-11e8-924b-0cc47ab2a092
spec:
  backend:
    serviceName: web
    servicePort: 80
  rules:
  - host: web.0cd48889-850d-4ae1-bd1c-0b37a315783d.147-75-89-53.aksh.io
status:
  loadBalancer:
    ingress:
    - ip: 147.75.89.53
```

**Comment by gosuri** [comment]
fixed: the problem was in the SDL file, the `accept` parameter should be under `expose`.

bad config:
```yaml
...
services:
  web:
    image: quay.io/ovrclk/demo-app
    accept:
      - example.com
    expose:
      - port: 80
        as: 80
        to:
          - global: true
...
```
fixed config:
```yaml
...
services:
  web:
    image: quay.io/ovrclk/demo-app
    expose:
      - port: 80
        as: 80
        accept:
          - example.com
        to:
          - global: true
...
```
