### ISSUE TITLE
sdl: improve errors while parsing

### ISSUE THREAD

**Issue by gosuri** [ovrclk/akash#352]
Better error messages while parsing SDL will be great. For example: I accidentally had the `accept` in the wrong place that caused issues with my hostname not resolving, the `accept` parameter should be under `expose`.

bad config:
```yaml
...
services:
  web:
    image: quay.io/ovrclk/demo-app
    accept:
      - example.com
    expose:
      - port: 80
        as: 80
        to:
          - global: true
...
```
fixed config:
```yaml
...
services:
  web:
    image: quay.io/ovrclk/demo-app
    expose:
      - port: 80
        as: 80
        accept:
          - example.com
        to:
          - global: true
...
```
