### ISSUE TITLE
odd routing behavior with hostname assignments

### ISSUE THREAD

**Issue by gosuri** [ovrclk/akash#388]
both deployments serve the same app

##  curl -s hello.147.75.91.165.nip.io | grep title

```
  <title>Greg Osuri</title>
  <link rel="alternate" type="application/rss+xml" title="Greg Osuri" href="http://0.0.0.0:8080/feed.xml" />
    <a class="site-title" href="/">Greg Osuri</a>

```
## curl -s osuri.147.75.91.165.nip.io | grep title
```
  <title>Greg Osuri</title>
  <link rel="alternate" type="application/rss+xml" title="Greg Osuri" href="http://0.0.0.0:8080/feed.xml" />
    <a class="site-title" href="/">Greg Osuri</a>

```
## traefik logs:

```
kube-system/traefik-d869575c8-pjpsj[traefik]: {"level":"warning","msg":"Error in ingress: HTTP is nil","time":"2019-10-15T01:51:54Z"}
kube-system/traefik-d869575c8-pjpsj[traefik]: {"level":"warning","msg":"Error in ingress: HTTP is nil","time":"2019-10-15T01:51:54Z"}
kube-system/traefik-d869575c8-pjpsj[traefik]: {"level":"warning","msg":"Error in ingress: HTTP is nil","time":"2019-10-15T01:51:54Z"}
kube-system/traefik-d869575c8-pjpsj[traefik]: {"level":"error","msg":"Error creating global backend for ingress 05ce2316609b0853cce29cfcb3c7b644f2e36bf2/web: endpoints not available for 05ce2316609b0853cce29cfcb3c7b644f2e36bf2/web","time":"2019-10-15T01:51:54Z"}
kube-system/traefik-d869575c8-pjpsj[traefik]: {"level":"error","msg":"Error creating global backend for ingress 7307e1294396362eb597a5d63cc106d210874449/web: duplicate backend: global-default-backend","time":"2019-10-15T01:51:54Z"}
kube-system/traefik-d869575c8-pjpsj[traefik]: {"level":"info","msg":"Server configuration reloaded on :80","time":"2019-10-15T01:51:54Z"}
kube-system/traefik-d869575c8-pjpsj[traefik]: {"level":"info","msg":"Server configuration reloaded on :443","time":"2019-10-15T01:51:54Z"}
kube-system/traefik-d869575c8-pjpsj[traefik]: {"level":"info","msg":"Server configuration reloaded on :8080","time":"2019-10-15T01:51:54Z"}
kube-system/traefik-d869575c8-pjpsj[traefik]: {"level":"warning","msg":"Error in ingress: HTTP is nil","time":"2019-10-15T01:51:56Z"}
kube-system/traefik-d869575c8-pjpsj[traefik]: {"level":"info","msg":"Updated status on ingress 05ce2316609b0853cce29cfcb3c7b644f2e36bf2/web","time":"2019-10-15T01:51:56Z"}
kube-system/traefik-d869575c8-pjpsj[traefik]: {"level":"error","msg":"Error creating global backend for ingress 7307e1294396362eb597a5d63cc106d210874449/web: duplicate frontend: global-default-frontend","time":"2019-10-15T01:51:56Z"}
kube-system/traefik-d869575c8-pjpsj[traefik]: {"level":"warning","msg":"Error in ingress: HTTP is nil","time":"2019-10-15T01:51:56Z"}
kube-system/traefik-d869575c8-pjpsj[traefik]: {"level":"error","msg":"Error creating global backend for ingress 05ce2316609b0853cce29cfcb3c7b644f2e36bf2/web: duplicate frontend: global-default-frontend","time":"2019-10-15T01:51:56Z"}
kube-system/csi-packet-controller-0[csi-external-provisioner]: I1015 01:51:56.548747       1 reflector.go:389] sigs.k8s.io/sig-storage-lib-external-provisioner/controller/controller.go:807: Watch close - *v1.StorageClass total 0 items received
kube-system/traefik-d869575c8-pjpsj[traefik]: {"level":"info","msg":"Server configuration reloaded on :80","time":"2019-10-15T01:51:56Z"}
kube-system/traefik-d869575c8-pjpsj[traefik]: {"level":"info","msg":"Server configuration reloaded on :443","time":"2019-10-15T01:51:56Z"}
kube-system/traefik-d869575c8-pjpsj[traefik]: {"level":"info","msg":"Server configuration reloaded on :8080","time":"2019-10-15T01:51:56Z"}
```

## blog.yml
```
---
version: "1.0"

services:
  web:
    image: gosuri/blog
    expose:
      - port: 8080
        as: 80
        accept:
          - osuri.147.75.91.165.nip.io
        to:
          - global: true

profiles:
  compute:
    web:
      cpu: "100m"
      memory: "512Mi"
      disk: "1Gi"
  placement:
    attributes:
      region: sfo
      sgx: enabled
    global:
      pricing:
        web: 200u

deployment:
  web:
    global:
      profile: web
      count: 2
```

## deployment.yml

```
---
version: "1.0"

services:
  web:
    image: quay.io/ovrclk/demo-app
    expose:
      - port: 80
        as: 80
        accept:
          - hello.147.75.91.165.nip.io
        to:
          - global: true

profiles:
  compute:
    web:
      cpu: "0.25"
      memory: "128Mi"
      disk: "1Gi"
  placement:
    attributes:
      region: sfo
      sgx: enabled
    global:
      pricing:
        web: 100u

deployment:
  web:
    global:
      profile: web
      count: 2

```
## `akash deployment create blog.yml -k gosuri`:

```
(wait)  [deploy] begin deployment from config: (...)
(wait)  [broadcast] request deployment for group(s): global
(done)  [broadcast] request accepted, deployment created with id: 1d5aba9751bae1bd037614d1edc28f535d7542646878b2e841ab5a9aabad5476
(wait)  [auction] waiting to create buy orders(s) for 1 deployment groups(s)
(wait)  [auction] buy order (1) created with id: 1d5aba9751bae1bd037614d1edc28f535d7542646878b2e841ab5a9aabad5476/1/2
(wait)  [auction] waiting on fulfillment(s)
(wait)  [auction] received fulfillment (1/1) with id:
        1d5aba9751bae1bd037614d1edc28f535d7542646878b2e841ab5a9aabad5476/1/2/9bd3ca608ed40db3d0cd7c1d352df9b60adf9ca759458991102bf389b5404eee
(wait)  [lease] waiting on lease(s)
(done)  [auction] complete; received 1 fulfillment(s) for 1 order(s)
(wait)  [lease] received lease (1) for group (1/1) [price 90] [id
        1d5aba9751bae1bd037614d1edc28f535d7542646878b2e841ab5a9aabad5476/1/2/9bd3ca608ed40db3d0cd7c1d352df9b60adf9ca759458991102bf389b5404eee]
(wait)  [lease] send manifest to provider at http://locke.akashtest.net
(done)  [lease] manifest accepted by provider at http://locke.akashtest.net
(done)  [lease] complete; received 1 lease(s) for 1 groups(s)
(done)  [deploy] deployment complete

Deployment
==========

Deployment ID:        	1d5aba9751bae1bd037614d1edc28f535d7542646878b2e841ab5a9aabad5476
Deployment Groups(s): 	Group:        	global
                      	Requirements:
                      	Resources:    	Count:  	2
                      	              	Price:  	200
                      	              	CPU:    	100
                      	              	Memory: 	536870912
                      	              	Disk:   	1073741824
Fulfillment(s):       	Group:    	1
                      	Price:    	90
                      	Provider: 	9bd3ca608ed40db3d0cd7c1d352df9b60adf9ca759458991102bf389b5404eee

Lease(s)
========

Lease ID:    	1d5aba9751bae1bd037614d1edc28f535d7542646878b2e841ab5a9aabad5476/1/2/9bd3ca608ed40db3d0cd7c1d352df9b60adf9ca759458991102bf389b5404eee
Services(s): 	NAME 	HOST(S) / IP(S)           	AVAILABLE	TOTAL
             	web  	osuri.147.75.91.165.nip.io	2        	2
             	<nil>	147.75.91.165             	<nil>    	<nil>
```
