### ISSUE TITLE
akashctl events: show module, action

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#718]
`akashctl events` currently shows:

```
id:
  owner: akash1uaamq2yk53y0pkykp9h8dq2u3sa2y5g5ec8242
  dseq: 100971
  gseq: 1
  oseq: 1
  provider: akash1sz43rlut99r8l7rfkej8cqxa66arqkhra2v4cp
price:
  denom: akash
  amount: "1000"

id:
  owner: akash1uaamq2yk53y0pkykp9h8dq2u3sa2y5g5ec8242
  dseq: 100971
  gseq: 1
  oseq: 1
  provider: akash1sz43rlut99r8l7rfkej8cqxa66arqkhra2v4cp
price:
  denom: akash
  amount: "1000"
```

we also want to show the `module` and `action` of each event.
