### ISSUE TITLE
Provider: lease-status 500 internal error

### ISSUE THREAD

**Issue by Ropes** [ovrclk/akash#923]
There is some odd behavior coming from the Provider's `lease-status` response. HTTP 500s are being returned for an active lease. Unfortunately, I have not been able to reproduce this behavior locally via the kind environments. 

In addtion, testing edgenet with a bad token denom `akash` resulted in a lease in the state of `insufficient_funds`. #920 should provide better protection from such errors though.
```
akash --home=$AKASH_HOME --node=$AKASH_NODE query market  lease list                                                                                                                                                                                    
leases:                                                                                                                                                                                                                                                       
- lease_id:                                                                                                                                                                                                                                                   
    dseq: "327679"                                                                                                                                                                                                                                            
    gseq: 1                                                                                                                                                                                                                                                   
    oseq: 1                                                                                                                                                                                                                                                   
    owner: akash1664w3hsvgy70ftt27xejmkxe8tken9mlyqnhwz                                                                                                                                                                                                       
    provider: akash1439fss4e6xhj8pzf2t20lyu92570flgdarze5x                                                                                                                                                                                                    
  price:                                                                                                                                                                                                                                                      
    amount: "525"                                                                                                                                                                                                                                             
    denom: akash                                                                                                                                                                                                                                              
  state: insufficient_funds                                                                                                                                                                                                                                   
- lease_id:                                                                                                                                                                                                                                                   
    dseq: "328119"                                                                                                                                                                                                                                            
    gseq: 1                                                                                                                                                                                                                                                   
    oseq: 1                                                                                                                                                                                                                                                   
    owner: akash1664w3hsvgy70ftt27xejmkxe8tken9mlyqnhwz                                                                                                                                                                                                       
    provider: akash1439fss4e6xhj8pzf2t20lyu92570flgdarze5x                                                                                                                                                                                                    
  price:                                                                                                                                                                                                                                                      
    amount: "605"                                                                                                                                                                                                                                             
    denom: uakt                                                                                                                                                                                                                                               
  state: active                                                                                                                                                                                                                                               
- lease_id:                                                                                                                                                                                                                                                   
    dseq: "241702"                                                                                                                                                                                                                                            
    gseq: 1                                                                                                                                                                                                                                                   
    oseq: 1                                                                                                                                                                                                                                                   
    owner: akash1aqceppwz47c9gqrjkm73pkuzlm89mczkdl669a                                                                                                                                                                                                       
    provider: akash1439fss4e6xhj8pzf2t20lyu92570flgdarze5x                                                                                                                                                                                                    
  price:                                                                                                                                                                                                                                                      
    amount: "8081"                                                                                                                                                                                                                                            
    denom: uakt                                                                                                                                                                                                                                               
  state: closed           
```
Requesting the status of a lease results in a 500 Internal Error returned:
```
akash --home=$AKASH_HOME  --node=$AKASH_NODE provider lease-status --dseq=328119 --gseq=1 --oseq=1 --owner=akash1664w3hsvgy70ftt27xejmkxe8tken9mlyqnhwz --provider=akash1439fss4e6xhj8pzf2t20lyu92570flgdarze5x --trace
Error: server response: 500 Internal Server Error
Usage:
  akash provider lease-status [flags]...
```
The provider daemon logs no error messages, so all we have to go on is `Error: server response: 500 Internal Server Error
Usage:` which does not provide much information.

Nominal /status request is functional:
```
akash --home=$AKASH_HOME  --node=$AKASH_NODE provider status --provider="akash1439fss4e6xhj8pzf2t20lyu92570flgdarze5x" --trace                                                                                                                                
{                                                                                                                                                                                                                                                             
  "cluster": {                                                                                                                                                                                                                                                
    "leases": 1,                                                                                                                                                                                                                                              
    "inventory": {                                                                                                                                                                                                                                            
      "active": [                                                                                                                                                                                                                                             
        {  ....                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
```

After digging through code I have not located an obvious cause, at the K8s API level, of why `lease-status`'s service endpoint would return an internal error. So I've added some logging of Kubernetes Client errors so that they'll show up in the Provider's logs.

## Action Items
* [x] Re-deploy edgenet + providers
* [x] Always check the `provider lease-status` endpoint, and if error, check the provider's logs.

If `akash provider lease-status` continues to fail, we need to investigate this thoroughly.
