### ISSUE TITLE
edgenet: manifest validation failed

### ISSUE THREAD

**Issue by troian** [ovrclk/akash#937]
```
E[2020-11-26|16:07:43.393] invalid manifest                             module=manifest-manager deployment=akash1x063d5ta37lrcwmes4xylg52wgcvch5q8r709s/39144 err="invalid manifest: mismatch on number of endpoints 1 != 0"
```

manifest
```yaml
---
version: "2.0"
services:
  web:
    image: fager/retwis
    expose:
      - port: 8080
        as: 8080
        accept:
          - hello.localhost 
        to:
          - global: true
profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 256Mi
        storage:
          size: 256Mi
  placement:
    westcoast:
      attributes:
        region: us-west
        organization: ovrclk.com
          #      signedBy:
          #allOf:
          #- akash1vz375dkt0c60annyp6mkzeejfq0qpyevhseu05
      pricing:
        web: 
          denom: uakt
          amount: 9000
deployment:
  web:
    westcoast:
      profile: web
      count: 1
```
