### ISSUE TITLE
running "akash query market lease get" asks for the provider

### ISSUE THREAD

**Issue by hydrogen18** [ovrclk/akash#939]
Running the command `akash query market lease get` results in the command asking for the provider. This doesn't make sense as one intended usage of this is to allow the user to figure out what provider has the specified lease

e.g.

```
 ../../akash --home ./cache --node=http://rpc-edgenet.akashdev.net:26657 query market lease get --owner akash1x063d5ta37lrcwmes4xylg52wgcvch5q8r709s --dseq 39122 --gseq 1 --oseq 1
Error: required flag(s) "provider" not set
```

**Comment by boz** [comment]
the thing is, there could be more than one lease for an order.  perhaps it should default to the current, active lease.

This also goes for `provider lease-status`, `provider send-manifest` - it's even more clear there, it for the most part should only deal with the active lease.

**Comment by hydrogen18** [comment]
What I was basically looking for here was a way to get the provider(s) from owner, dseq, gseq, & oseq. I did some poking around in the market code and figured out if you do

```
akash --home ./cache query market lease list --owner     "akash14dkxfa74fa2v7nmwvay0falv4s56aecuxwl4yg" --dseq 1 --gseq 1 --oseq 1
```

You'll get results like this 

```
leases:
- lease_id:
    dseq: "1"
    gseq: 1
    oseq: 1
    owner: akash14dkxfa74fa2v7nmwvay0falv4s56aecuxwl4yg
    provider: akash1wztupg65uhzd0kjfkg9wnsdmuxn4zspv8zmx5g
  price:
    amount: "624"
    denom: uakt
  state: active
pagination:
  next_key: null
  total: "0"
```

That command gives you a way to go from the information you already know about the lease to figuring out which provider(s) have fulfilled the lease. So I don't think any changes are really necessary at the this time. 

It seems like presently `akash query market lease get` is redundant however. You can get the same thing by just substituting `akash query market lease list`.
