### ISSUE TITLE
service: allow mounting files

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#959]
Allow mounting files into a container.

Add a new section to the [service section in sdl](https://github.com/ovrclk/akash/blob/master/_docs/sdl.md#services):

```yaml
mounts:
  - path: /config/app.toml
    contents: |-
      foo=bar
      baz=boo
```

In k8s, create a configmap with the given contents and mount it at the given path.

To start, these can be mounted read-only.
