### ISSUE TITLE
audit: field names seem backwards

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#970]
In the audit below, the provider address is `akash1ds82uk3pzawavlasc2qd88luewzye2qrcwky7t` and the signer address is `akash1vz375dkt0c60annyp6mkzeejfq0qpyevhseu05`, but they are labeled oppositely.

```yaml
- attributes:
  - key: organization
    value: ovrclk.com
  - key: region
    value: us-west
  owner: akash1ds82uk3pzawavlasc2qd88luewzye2qrcwky7t
  validator: akash1vz375dkt0c60annyp6mkzeejfq0qpyevhseu05
```

**Comment by troian** [comment]
🤔 
```yaml
- name: main
  type: local
  address: akash1vz375dkt0c60annyp6mkzeejfq0qpyevhseu05
  pubkey: akashpub1addwnpepqt9p7t87g4t3pqe0gwf3mtx4c6tnf98zmp6vwssae6a67u4detanql3cm2y
  mnemonic: ""
  threshold: 0
  pubkeys: []
- name: provider5
  type: local
  address: akash1ds82uk3pzawavlasc2qd88luewzye2qrcwky7t
  pubkey: akashpub1addwnpepq07szm402h8mydzl4t539zwqvqsktw4xz7mwem4z8dx6ce30th27z0ue53q
  mnemonic: ""
  threshold: 0
  pubkeys: []
```
