### ISSUE TITLE
audited attributes not preventing matching

### ISSUE THREAD

**Issue by boz** [ovrclk/akash#973]
So, I think that this is related to #970 - it's probably a simple check that's backwards.

In testnet, I deleted the audited attributes for provider 5, but after I did that provider 5 still won a lease.  At that time, the `akash query audit list` returned this:

```yaml
pagination:
  next_key: null
  total: "0"
providers:
- attributes:
  - key: organization
    value: ovrclk.com
  - key: region
    value: us-west
  owner: akash1y8xhp9ekxctahvex7842h607lmwp50q0n89tw0
  validator: akash1vz375dkt0c60annyp6mkzeejfq0qpyevhseu05
- attributes:
  - key: organization
    value: ovrclk.com
  - key: region
    value: us-central
  owner: akash15ql9ycjkkxhpc2nxtnf78qqjguwzz8gc4ue7wl
  validator: akash1vz375dkt0c60annyp6mkzeejfq0qpyevhseu05
- attributes:
  - key: organization
    value: ovrclk.com
  - key: region
    value: us-west
  owner: akash1uu8wfvxscqt7ax89hjkxral0r2k73c6ee97dzn
  validator: akash1vz375dkt0c60annyp6mkzeejfq0qpyevhseu05
- attributes:
  - key: organization
    value: ovrclk.com
  - key: region
    value: us-central
  owner: akash174hxdpuxsuys9qkauaf57ym5j8dm4secnz6jd7
  validator: akash1vz375dkt0c60annyp6mkzeejfq0qpyevhseu05
```

Provider 5's address, `akash1ds82uk3pzawavlasc2qd88luewzye2qrcwky7t`, is not in that list, but I suspect that the logic is confusing the signing address with the validator somewhere and incorrectly determining that there are indeed audited attributes from the signer for the provider.

**Comment by boz** [comment]
I don't have his second lease but I do have the first one:

```json
{"lease_id":{"owner":"akash10cwmzwvkfcvmtj5egexqvcgcpardg3aufqjacj","dseq":"31691","gseq":1,"oseq":1,"provider":"akash1ds82uk3pzawavlasc2qd88luewzye2qrcwky7t"},"state":"active","price":{"denom":"uakt","amount":"219"}}
```

```sh
akash query market order list --owner akash10cwmzwvkfcvmtj5egexqvcgcpardg3aufqjacj
orders:
- close_at: "44040"
  order_id:
    dseq: "31691"
    gseq: 1
    oseq: 1
    owner: akash10cwmzwvkfcvmtj5egexqvcgcpardg3aufqjacj
  spec:
    name: westcoast
    order_bid_duration: "12342"
    requirements:
      attributes:
      - key: organization
        value: ovrclk.com
      signed_by:
        all_of: []
        any_of:
        - akash1vz375dkt0c60annyp6mkzeejfq0qpyevhseu05
    resources:
    - count: 1
      price:
        amount: "1000"
        denom: uakt
      resources:
        cpu:
          attributes: []
          units:
            val: "100"
        endpoints: []
        memory:
          attributes: []
          quantity:
            val: "536870912"
        storage:
          attributes: []
          quantity:
            val: "536870912"
  start_at: "31698"
  state: matched
- close_at: "54855"
  order_id:
    dseq: "42506"
    gseq: 1
    oseq: 1
    owner: akash10cwmzwvkfcvmtj5egexqvcgcpardg3aufqjacj
  spec:
    name: westcoast
    order_bid_duration: "12342"
    requirements:
      attributes:
      - key: organization
        value: ovrclk.com
      signed_by:
        all_of: []
        any_of:
        - akash1vz375dkt0c60annyp6mkzeejfq0qpyevhseu05
    resources:
    - count: 1
      price:
        amount: "1000"
        denom: uakt
      resources:
        cpu:
          attributes: []
          units:
            val: "100"
        endpoints: []
        memory:
          attributes: []
          quantity:
            val: "536870912"
        storage:
          attributes: []
          quantity:
            val: "536870912"
  start_at: "42513"
  state: matched
pagination:
  next_key: null
  total: "0"
```

```sh
akash query market lease list --owner akash10cwmzwvkfcvmtj5egexqvcgcpardg3aufqjacj
leases:
- lease_id:
    dseq: "31691"
    gseq: 1
    oseq: 1
    owner: akash10cwmzwvkfcvmtj5egexqvcgcpardg3aufqjacj
    provider: akash1ds82uk3pzawavlasc2qd88luewzye2qrcwky7t
  price:
    amount: "219"
    denom: uakt
  state: active
- lease_id:
    dseq: "42506"
    gseq: 1
    oseq: 1
    owner: akash10cwmzwvkfcvmtj5egexqvcgcpardg3aufqjacj
    provider: akash174hxdpuxsuys9qkauaf57ym5j8dm4secnz6jd7
  price:
    amount: "234"
    denom: uakt
  state: active
pagination:
  next_key: null
  total: "0"
```

It looks like it's not a problem :shrug:

**Comment by troian** [comment]
yeah, looks like he sent log previous order as new.

if no attributes signed by deployment requires them, order remains open
```yaml
❯ make query-orders
../../akash --home "./cache" query market order list
orders:
- close_at: "12506"
  order_id:
    dseq: "1"
    gseq: 1
    oseq: 1
    owner: akash1jz3a2z7j5a79nqjvd7e3akzupuel9fhhhth0jz
  spec:
    name: westcoast
    order_bid_duration: "12342"
    requirements:
      attributes:
      - key: region
        value: us-west
      signed_by:
        all_of:
        - akash1jz3a2z7j5a79nqjvd7e3akzupuel9fhhhth0jz
        any_of: []
    resources:
    - count: 2
      price:
        amount: "1000"
        denom: uakt
      resources:
        cpu:
          attributes: []
          units:
            val: "100"
        endpoints: []
        memory:
          attributes: []
          quantity:
            val: "134217728"
        storage:
          attributes: []
          quantity:
            val: "268435456"
  start_at: "164"
  state: open
pagination:
  next_key: null
  total: "0"
```
